// Danmaku Radar - Tencent CloudBase Node.js HTTP Cloud Function (free test)
// Reads the daily snapshot generated by GitHub Actions. Subscriptions are
// intentionally temporary on the free function filesystem.
const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = Number(process.env.PORT || 9000);
const SNAPSHOT_URL = process.env.DANMAKU_SNAPSHOT_URL ||
  'https://raw.githubusercontent.com/cffjzsb6r7-cloud/danmaku-radar/main/data/latest.json';
const HISTORY_URL = process.env.DANMAKU_HISTORY_URL ||
  'https://raw.githubusercontent.com/cffjzsb6r7-cloud/danmaku-radar/main/data/history.json';
const SUBSCRIBERS_FILE = path.join('/tmp', 'danmaku-subscribers.json');
let snapshotCache = null;
let snapshotAt = 0;
let historyCache = null;

function localJson(filename) {
  try { return JSON.parse(fs.readFileSync(path.join(__dirname, filename), 'utf8')); }
  catch (_) { return null; }
}

function json(res, status, body) {
  const data = JSON.stringify(body);
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'no-store',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type,Authorization'
  });
  res.end(data);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let raw = '';
    req.on('data', chunk => { raw += chunk; if (raw.length > 256 * 1024) req.destroy(); });
    req.on('end', () => resolve(raw));
    req.on('error', reject);
  });
}

async function fetchJson(url) {
  const response = await fetch(url, { headers: { 'User-Agent': 'danmaku-radar-cloudbase/1.0' } });
  if (!response.ok) throw new Error(`snapshot ${response.status}`);
  return response.json();
}

async function snapshot() {
  if (snapshotCache && Date.now() - snapshotAt < 5 * 60 * 1000) return snapshotCache;
  const local = localJson('latest.json');
  if (local) { snapshotCache = local; snapshotAt = Date.now(); return snapshotCache; }
  try {
    snapshotCache = await fetchJson(SNAPSHOT_URL);
    snapshotAt = Date.now();
    return snapshotCache;
  } catch (error) {
    if (snapshotCache) return snapshotCache;
    throw error;
  }
}

async function history() {
  if (historyCache) return historyCache;
  const local = localJson('history.json');
  if (local) { historyCache = local; return historyCache; }
  historyCache = await fetchJson(HISTORY_URL);
  return historyCache;
}

function loadSubscribers() {
  try { return JSON.parse(fs.readFileSync(SUBSCRIBERS_FILE, 'utf8')); }
  catch (_) { return []; }
}

function saveSubscribers(items) {
  fs.writeFileSync(SUBSCRIBERS_FILE, JSON.stringify(items), 'utf8');
}

async function handle(req, res) {
  if (req.method === 'OPTIONS') return json(res, 204, {});
  const url = new URL(req.url || '/', 'http://cloudbase.local');
  const route = url.pathname.replace(/\/+$/, '') || '/';
  try {
    if (route === '/') return json(res, 200, { name: 'danmaku-radar-api', ok: true });
    if (route === '/api/health') {
      return json(res, 200, { ok: true, source: 'github-actions-snapshot', stale: false });
    }
    if (route === '/api/trends') return json(res, 200, await snapshot());
    if (route === '/api/history') return json(res, 200, await history());
    if (route === '/api/stats') {
      const data = await snapshot();
      return json(res, 200, {
        ok: true,
        posts: (data.content_rank || []).length,
        topics: (data.topic_rank || []).length,
        hot_search: (data.hot_search || []).length,
        danmaku_words: (data.danmaku_words || []).length,
        week: data.week || '', last_fetch: data.last_fetch || ''
      });
    }
    if (route === '/api/subscribe' && req.method === 'POST') {
      const body = JSON.parse((await readBody(req)) || '{}');
      const email = String(body.email || '').trim().toLowerCase();
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
        return json(res, 400, { ok: false, msg: '邮箱格式不正确' });
      }
      const items = loadSubscribers();
      if (!items.some(item => item.email === email)) items.push({ email, lang: body.lang || 'both', subscribed_at: new Date().toISOString() });
      saveSubscribers(items);
      return json(res, 200, { ok: true, msg: '订阅成功（测试版临时保存）' });
    }
    return json(res, 404, { ok: false, msg: 'Not Found' });
  } catch (error) {
    return json(res, 502, { ok: false, msg: '数据源暂时不可用', detail: String(error.message || error) });
  }
}

http.createServer((req, res) => { handle(req, res); }).listen(PORT, '0.0.0.0', () => {
  console.log(`danmaku-radar cloud function listening on ${PORT}`);
});
